### ISSUE TITLE
BUG: Not reloading Model in Module

### ISSUE THREAD

**Issue by dominikchrastek** [fluxxu/elm-hot-loader#28]
Hello, I have folder structure similar like here:
https://github.com/rogeriochaves/structured-elm-todomvc/tree/modular

The problem is: when I change my model in some Module, it will reload, but the changes are not applied to the model (view and update are working properly, but the model isn't).

When I try it without `elm-hot-loader`, it works.

**Comment by fluxxu** [comment]
Hi,

I think the problem you described is expected behavior. All this loader do is to call your view functions with saved model data (before code change). So if you change your model, it still uses old model data to call view functions.
If you remove elm-hot-loader, webpack will reload the whole page, everything got re-initialized, so it works.
Hopefully one day Elm compiler will include perfect hot reload feature so we can ditch this loader because it's just a hack.
