### ISSUE TITLE
Turn into starter kit

### ISSUE THREAD

**Issue by simonh1000** [fluxxu/elm-hot-loader#3]
I'm very excited about the hotloading and want to use your project as a starter, but your setup is confusing, given that I know nothing about webpack (some of the key config info is at the root level, and some at the `/example` level). 

I'd rather you set up the code with a `/src` (rather than `/example`) directory and have a production script available for final deployment (that perhaps copies the compiled assets into an `/dist`) in the root package.json file. 

I have had a go at https://github.com/simonh1000/elm-hot-loader.

What do you think?

**Comment by fluxxu** [comment]
Hi!

I don't think it's a good idea to rename /example folder here to /src, because this repository is for the webpack-hot-loader itself. If there is a '/src' folder here, I'll assume it is the source code of loader, not the source code of example(which depends on loader).

But I agree with you that the example here is confusing, so I made another repository here:
https://github.com/fluxxu/elm-hot-loader-starter

BTW, you can remove hmr.js and index.js from your fork because these two files already included in node_modules.

Thanks :)

**Comment by simonh1000** [comment]
OK, Cool, thanks
